server:
  port: 8089
#多数据源配置
spring:
  #数据库配置
  datasource:
    mysql:
      #用户数据库配置，存放用户数据
      download:
        jdbcUrl: jdbc:mysql://117.48.197.114:3306/sandman_download?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: sunpeikai
        password: spkzq521
        driver-class-name: com.mysql.jdbc.Driver
      #系统数据库配置，存放用户账户信息及权限信息
      system:
        jdbcUrl: jdbc:mysql://117.48.197.114:3306/sandman_sys?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: sunpeikai
        password: spkzq521
        driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: prod
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml